### ISSUE TITLE
Error building on OSX 10.13.6 

### ISSUE THREAD

**Issue by znetstar** [justadudewhohacks/opencv4nodejs#415]
I'm unable to build on OSX 10.13.6 (High Sierra).

With the autobuild enabled I get:
```
In file included from ../cc/opencv4nodejs.cc:24:
In file included from ../cc/modules/text/text.h:3:
../cc/modules/text/OCRHMMClassifier.h:5:10: fatal error: 'opencv2/text.hpp' file not found
#include <opencv2/text.hpp>
         ^~~~~~~~~~~~~~~~~~
```

And with the autobuild disabled I get:
```
In file included from ../cc/modules/face/Facemark.cc:4:
../cc/modules/face/FacemarkBindings.h:22:23: error: no member named 'addTrainingSample' in 'cv::face::Facemark'
      results = self->addTrainingSample(image, landmarks);
                ~~~~  ^
../cc/modules/face/FacemarkBindings.h:63:13: error: no member named 'getData' in 'cv::face::Facemark'
      self->getData(&data);
      ~~~~  ^
../cc/modules/face/FacemarkBindings.h:82:13: error: no member named 'getFaces' in 'cv::face::Facemark'
      self->getFaces(image, faces);
      ~~~~  ^
../cc/modules/face/FacemarkBindings.h:103:13: error: no member named 'training' in 'cv::face::Facemark'
      self->training();
      ~~~~  ^
../cc/modules/face/Facemark.cc:117:9: error: no member named 'setFaceDetector' in 'cv::face::Facemark'
      ->setFaceDetector((cv::face::FN_FaceDetector)detector, callback);
```

justadudewhohacks/opencv4nodejs installs cleanly.

Let me know if I can provide any additional info that would be of use.

**Comment by znetstar** [comment]
This is for the @a-sync/opencv4nodejs package
